### ISSUE TITLE
Still getting ConcurrentModificationException during startup for OedtDatabase with 9.3.3

### ISSUE THREAD

**Issue by mikefechner** [omecra/de.omecra.oedt.updatesite#101]

**Comment by mikefechner** [comment]
I'm still seeing this with 9.3.3:

!ENTRY org.eclipse.core.jobs 4 2 2020-06-22 21:12:24.880
!MESSAGE An internal error occurred during: "Update Oedt Database Project ABL".
!STACK 0
java.util.ConcurrentModificationException
	at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1495)
	at java.base/java.util.HashMap$EntryIterator.next(HashMap.java:1528)
	at java.base/java.util.HashMap$EntryIterator.next(HashMap.java:1526)
	at java.base/java.util.Collection.removeIf(Collection.java:544)
	at com.openedge.pdt.project.properties.ConfigFileManager.getConfigFileStatus(ConfigFileManager.java:64)
	at com.openedge.pdt.project.properties.ConfigFileManager.isProjectConfigUsable(ConfigFileManager.java:88)
	at com.openedge.pdt.project.sharedavm.SharedAVM.getProjectsUsingSharedAVM(SharedAVM.java:356)
	at com.openedge.pdt.project.sharedavm.SharedAVM.isSharedAVMProject(SharedAVM.java:326)
	at com.openedge.pdt.project.connection.DatabaseConnectionManager.getProjectDBConnectionProfiles(DatabaseConnectionManager.java:995)
	at com.openedge.pdt.project.OEProject.hasDatabases(OEProject.java:247)
	at de.omecra.oedt.internal.core.database.OedtDatabaseProjectManager.getAddedDatabases(OedtDatabaseProjectManager.java:374)
	at de.omecra.oedt.internal.core.database.OedtDatabaseProjectManager$2.run(OedtDatabaseProjectManager.java:151)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by lneumeier** [comment]
Fixed in 9.3.4
