### ISSUE TITLE
Out of memory exception while building source model

### ISSUE THREAD

**Issue by LievenDeFoor** [omecra/de.omecra.oedt.updatesite#179]
Hi,

I'm having an OutOfMemory exception while building the source model of a project:

```
!ENTRY org.eclipse.core.jobs 4 2 2024-02-06 09:49:04.127
!MESSAGE An internal error occurred during: "Parse Files for Project: xxx".
!STACK 0
java.lang.OutOfMemoryError: Java heap space
	at java.base/java.lang.StringCoding$StringDecoder.decode(StringCoding.java:201)
	at java.base/java.lang.StringCoding.decode(StringCoding.java:344)
	at java.base/java.lang.String.<init>(String.java:592)
	at java.base/java.lang.String.<init>(String.java:614)
	at de.omecra.oedt.internal.core.project.model.builder.OedtSourceFileParser.parseFile(OedtSourceFileParser.java:73)
	at de.omecra.oedt.internal.core.project.model.builder.OedtSourceFileParser.parseFile(OedtSourceFileParser.java:59)
	at de.omecra.oedt.internal.core.project.model.builder.OedtSourceFileParser$1.run(OedtSourceFileParser.java:307)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

Current eclipse memory settings:
-Xms256m
-Xmx1024m

Any idea where to start looking for the cause?

Regards,
Lieven

**Comment by LievenDeFoor** [comment]
It appears the issue isn't solved after all...
Still occasional OutOfMemory and StackOverflow exceptions...

**Comment by lneumeier** [comment]
Both call-stacks point to reading the content of a file. Do you have a very big file inside your project?

**Comment by LievenDeFoor** [comment]
There are some git repositories with large pack files in there. They should be ignored/excluded but I'll check again.
Also some large log files apparently, I'll remove them.
I'll report back!

**Comment by LievenDeFoor** [comment]
I removed the large log files, checked that .git folders are excluded using resource filters and disabled Eclipse validators, as these seemed to be problematic on some files as well. Seems fixed...
