### ISSUE TITLE
An internal error occurred during: "Compute launch button tooltip"

### ISSUE THREAD

**Issue by LievenDeFoor** [omecra/de.omecra.oedt.updatesite#56]
When hovering the mouse over the Run configurations button I get:

![image](https://user-images.githubusercontent.com/8639525/55319044-60e3eb80-5474-11e9-81f7-02ff46ec8c3e.png)

Launching the configuration works though...

!ENTRY org.eclipse.core.jobs 4 2 2019-04-01 09:27:03.458
!MESSAGE An internal error occurred during: "Compute launch button tooltip".
!STACK 0
java.lang.NullPointerException
	at de.omecra.oedt.ui.ablunit.property.OedtABLUnitFileTester.isTestClass(OedtABLUnitFileTester.java:31)
	at de.omecra.oedt.ui.ablunit.property.OedtABLUnitFileTester.test(OedtABLUnitFileTester.java:17)
	at org.eclipse.core.internal.expressions.Property.test(Property.java:58)
	at org.eclipse.core.internal.expressions.TestExpression.evaluate(TestExpression.java:100)
	at org.eclipse.core.internal.expressions.CompositeExpression.evaluateAnd(CompositeExpression.java:51)
	at org.eclipse.core.internal.expressions.IterateExpression.evaluate(IterateExpression.java:160)
	at org.eclipse.core.internal.expressions.CompositeExpression.evaluateAnd(CompositeExpression.java:51)
	at org.eclipse.core.internal.expressions.WithExpression.evaluate(WithExpression.java:75)
	at org.eclipse.core.internal.expressions.CompositeExpression.evaluateAnd(CompositeExpression.java:51)
	at org.eclipse.core.internal.expressions.EnablementExpression.evaluate(EnablementExpression.java:55)
	at org.eclipse.debug.internal.ui.launchConfigurations.LaunchShortcutExtension.evalEnablementExpression(LaunchShortcutExtension.java:281)
	at org.eclipse.debug.internal.ui.contextlaunching.LaunchingResourceManager.getShortcutsForSelection(LaunchingResourceManager.java:454)
	at org.eclipse.debug.internal.ui.contextlaunching.LaunchingResourceManager.computeLabels(LaunchingResourceManager.java:240)
	at org.eclipse.debug.internal.ui.contextlaunching.LaunchingResourceManager$1$1.run(LaunchingResourceManager.java:142)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)

**Comment by LievenDeFoor** [comment]
Duplicate of #55

**Comment by lneumeier** [comment]
Lieven, can you post a screenshot of the button your are hovering. I'm not getting an error while I tried to reproduce the problem.

**Comment by LievenDeFoor** [comment]
![image](https://user-images.githubusercontent.com/8639525/55321050-f97c6a80-5478-11e9-81c8-6b71f18f5a26.png)

I'm getting the error on both Debug and Run configurations

**Comment by pruefer90** [comment]
I also have the same problem. It occurs with normal classes and testclasses, but does not occur when no editor is open.

**Comment by LievenDeFoor** [comment]
Yes, moving the focus back to the editor seems to be trigger to reproduce the error.

**Comment by lneumeier** [comment]
Are you using eclipse 64bit or 32bit?

@LievenDeFoor  I assume you are using Windows 7?
@pruefer90 What OS are you using?

**Comment by LievenDeFoor** [comment]
32-bit Eclipse on Windows 7

**Comment by pruefer90** [comment]
I'm using Windows 10 64-bit and also the 64-bit OpenEdge installation.

**Comment by lneumeier** [comment]
Well, I'm using Windows 10 and 64Bit Openedge too, but I can not reproduce this problem. However, I will include additional NP Checks to fix this problem.
