### ISSUE TITLE
Oedt Dependency build compile exception

### ISSUE THREAD

**Issue by KevinHermansR** [omecra/de.omecra.oedt.updatesite#63]
My colleague has a problem when he merge from a feature to develop there is an exception in the OedtBuilder.

[OedtDependencyBuild.txt](https://github.com/omecra/de.omecra.oedt.updatesite/files/3207155/OedtDependencyBuild.txt)
![Error](https://user-images.githubusercontent.com/47971737/58171574-9b108300-7c96-11e9-8fcd-e7a7302b1e67.png)

From log details:
!ENTRY org.eclipse.core.jobs 4 2 2019-05-21 16:21:08.107
!MESSAGE An internal error occurred during: "Oedt Dependency Build Compile".
!STACK 0
java.lang.NullPointerException
      at com.openedge.pdt.project.builder.CompileJob.convertAnnotationsToMarkers(CompileJob.java:749)
      at com.openedge.pdt.project.builder.CompileJob.updateResourceMarkers(CompileJob.java:697)
      at com.openedge.pdt.project.builder.CompileJob.calculateProblemMarkers2(CompileJob.java:590)
      at com.openedge.pdt.project.builder.CompileJob.compile(CompileJob.java:263)
      at com.openedge.pdt.project.builder.CompileBuildTargetTask.checkAndBuildResources(CompileBuildTargetTask.java:55)
      at com.openedge.pdt.project.builder.CompileBuildTargetTask.execute(CompileBuildTargetTask.java:41)
      at de.omecra.oedt.internal.core.project.builder.OedtCompile.compileFileList(OedtCompile.java:277)
      at de.omecra.oedt.internal.core.project.builder.OedtDependencyBuild$3.runInWorkspace(OedtDependencyBuild.java:381)
      at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:39)
      at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

**Comment by lneumeier** [comment]
Seems like I have to wrap the call to the Progress API in try-catch block.

**Comment by lneumeier** [comment]
Fixed in 9.1.0
