### ISSUE TITLE
Error with empty testsuites

### ISSUE THREAD

**Issue by pruefer90** [omecra/de.omecra.oedt.updatesite#76]
The following empty testsuite causes an error message when "Rebuild Source Project Model" ist clicked:
```
@TestSuite(classes="").
CLASS TestSuiteError:
END CLASS.
```

The message is:
```
!MESSAGE An internal error occurred during: "Oedt Dependency Build for Project: Test".
!STACK 0
java.lang.StringIndexOutOfBoundsException: String index out of range: 0
	at java.lang.String.charAt(String.java:658)
	at de.omecra.oedt.internal.core.project.model.builder.OedtSourceCompilationUnitBuilder.createClassReferences(OedtSourceCompilationUnitBuilder.java:223)
	at de.omecra.oedt.internal.core.project.model.builder.OedtSourceCompilationUnitBuilder.createFileReferences(OedtSourceCompilationUnitBuilder.java:149)
	at de.omecra.oedt.internal.core.project.model.builder.OedtSourceCompilationUnitBuilder.buildCompilationUnit(OedtSourceCompilationUnitBuilder.java:121)
	at de.omecra.oedt.internal.core.project.model.builder.OedtSourceFileParser.parseFile(OedtSourceFileParser.java:78)
	at de.omecra.oedt.internal.core.project.model.builder.OedtSourceFileParser.parseFile(OedtSourceFileParser.java:57)
	at de.omecra.oedt.internal.core.project.builder.OedtDeltaBuild.checkAdditions(OedtDeltaBuild.java:66)
	at de.omecra.oedt.internal.core.project.builder.OedtDependencyBuild.getDeltaBuild(OedtDependencyBuild.java:232)
	at de.omecra.oedt.internal.core.project.builder.OedtDependencyBuild.access$0(OedtDependencyBuild.java:228)
	at de.omecra.oedt.internal.core.project.builder.OedtDependencyBuild$1.run(OedtDependencyBuild.java:156)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

```

**Comment by lneumeier** [comment]
Fixed in next version.
